==== Network Policy 

In a cluster using a *Kubernetes Container Network Interface (CNI)* plug-in that supports Kubernetes network policy, network isolation is controlled entirely by _NetworkPolicy_ objects. In OpenShift Container Platform 4.7, OpenShift SDN supports using network policy in its default network isolation mode.

By default, all pods in a project are accessible from other pods and network endpoints. To isolate one or more pods in a project, you can create _NetworkPolicy_ objects in that project to indicate the allowed incoming connections. Project administrators can create and delete _NetworkPolicy_ objects within their own project.

If a pod is matched by selectors in one or more _NetworkPolicy_ objects, then the pod will accept only connections that are allowed by at least one of those __NetworkPolicy__ objects. A pod that is not selected by any _NetworkPolicy_ objects is fully accessible.

When designing your network policy, refer to the following guidelines:

* Reduce the number of OVS flow rules by using namespaces to contain groups of pods that need to be isolated.

* _NetworkPolicy_ objects that select a whole namespace, by using the namespaceSelector or an empty podSelector, generate only a single OVS flow rule that matches the VXLAN virtual network ID (VNID) of the namespace.

* Keep the pods that do not need to be isolated in their original namespace, and move the pods that require isolation into one or more different namespaces.

* Create additional targeted cross-namespace network policies to allow the specific traffic that you do want to allow from the isolated pods.

===== Create _NetworkPolicy_

* Create a policy Rule

[source,yaml]
----
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: <policy-name> # <1>
spec:
  podSelector:
  ingress: []
----
<1> Add your policy name

===== Viewing _NetworkPolicy_

Viewing network policies
You can list the network policies in your cluster.

To view NetworkPolicy objects defined in your cluster, run the following command:

[source,yaml]
----
$ oc get networkpolicy
Example NetworkPolicy object
The following annotates an example NetworkPolicy object:


kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-27107 # <1>
spec:
  podSelector: 
    matchLabels:
      app: mongodb # <2>
  ingress:
  - from:
    - podSelector: 
        matchLabels:
          app: app # <4>
    ports: 
    - protocol: TCP
      port: 27017
----

<1> The name of the NetworkPolicy object.
<2> A selector describing the pods the policy applies to. The policy object can only select pods in the project that the NetworkPolicy object is defined.
<3> A selector matching the pods that the policy object allows ingress traffic from. The selector will match pods in any project.
<4> A list of one or more destination ports to accept traffic on.

